# Generated by Django 4.1.7 on 2023-03-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_search_delete_mesurements_delete_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Searchs',
        ),
    ]
